service: serverlessreactdev

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - Fn::Join:
            - ":"
            - - arn:aws:secretsmanager
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - secret:*

package:
  include:
    - dist/**

functions:
  gumroadping:
    handler: dist/gumroadPing.pingHandler
    events:
      - http:
          path: gumroadPing
          method: POST
          cors: true
